/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mark.http.server;

import com.mark.http.server.factories.HiContextFactory;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.net.InetSocketAddress;

public class App {

    public static void main(String[] args) throws IOException {

        InetSocketAddress address = new InetSocketAddress(8080);
        int backlog = 0;

        HttpServer httpServer = HttpServer.create(address, backlog);

        var hiContextFactory = new HiContextFactory();
        httpServer.createContext("/hi", hiContextFactory.create());

        // Listen
        httpServer.start();
    }
}
